/* tslint:disable */
/* eslint-disable */
/**
 * Chaos
 * Central Management API - publicly exposed set of APIs for managing deployments
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@qernal.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BadRequestResponseFields
 */
export interface BadRequestResponseFields {
    /**
     * 
     * @type {string}
     * @memberof BadRequestResponseFields
     */
    email?: string;
}

/**
 * Check if a given object implements the BadRequestResponseFields interface.
 */
export function instanceOfBadRequestResponseFields(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function BadRequestResponseFieldsFromJSON(json: any): BadRequestResponseFields {
    return BadRequestResponseFieldsFromJSONTyped(json, false);
}

export function BadRequestResponseFieldsFromJSONTyped(json: any, ignoreDiscriminator: boolean): BadRequestResponseFields {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'email': !exists(json, 'email') ? undefined : json['email'],
    };
}

export function BadRequestResponseFieldsToJSON(value?: BadRequestResponseFields | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'email': value.email,
    };
}

