/* tslint:disable */
/* eslint-disable */
/**
 * Chaos
 * Central Management API - publicly exposed set of APIs for managing deployments
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@qernal.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Conflict Response
 * @export
 * @interface ConflictResponse
 */
export interface ConflictResponse {
    /**
     * 
     * @type {string}
     * @memberof ConflictResponse
     */
    message: string;
}

/**
 * Check if a given object implements the ConflictResponse interface.
 */
export function instanceOfConflictResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "message" in value;

    return isInstance;
}

export function ConflictResponseFromJSON(json: any): ConflictResponse {
    return ConflictResponseFromJSONTyped(json, false);
}

export function ConflictResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConflictResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'message': json['message'],
    };
}

export function ConflictResponseToJSON(value?: ConflictResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'message': value.message,
    };
}

