/* tslint:disable */
/* eslint-disable */
/**
 * Chaos
 * Central Management API - publicly exposed set of APIs for managing deployments
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@qernal.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Deleted Response
 * @export
 * @interface DeletedResponse
 */
export interface DeletedResponse {
    /**
     * 
     * @type {string}
     * @memberof DeletedResponse
     */
    message: string;
}

/**
 * Check if a given object implements the DeletedResponse interface.
 */
export function instanceOfDeletedResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "message" in value;

    return isInstance;
}

export function DeletedResponseFromJSON(json: any): DeletedResponse {
    return DeletedResponseFromJSONTyped(json, false);
}

export function DeletedResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeletedResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'message': json['message'],
    };
}

export function DeletedResponseToJSON(value?: DeletedResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'message': value.message,
    };
}

