/**
 * Chaos
 * Central Management API - publicly exposed set of APIs for managing deployments
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@qernal.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http.ts';

/**
* Environment variable for function
*/
export class FunctionEnv {
    /**
    * Key name
    */
    'name': string;
    /**
    * Reference for the secret, it\'s split up into 4 main parts; - [1] \"projects:\" - This references which resource type the secret is within - [2] \"0a6b9ff3-6807-4820-b94b-5e1d7efcdd93\" - The project UUID the secret is within - [3] \"MY_SECRET\" - The name of the secret - [4] \"0\" - The revision of the secret to use 
    */
    'reference': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "reference",
            "baseName": "reference",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return FunctionEnv.attributeTypeMap;
    }

    public constructor() {
    }
}

