/**
 * Chaos
 * Central Management API - publicly exposed set of APIs for managing deployments
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@qernal.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http.ts';

/**
* Replica strategy
*/
export class FunctionReplicasAffinity {
    /**
    * If there are > 1 replica, make sure they\'re on different clusters
    */
    'cluster': boolean;
    /**
    * If there are > 1 replica, make sure they\'re on different clouds
    */
    'cloud': boolean;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "cluster",
            "baseName": "cluster",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "cloud",
            "baseName": "cloud",
            "type": "boolean",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return FunctionReplicasAffinity.attributeTypeMap;
    }

    public constructor() {
    }
}

