/**
 * Chaos
 * Central Management API - publicly exposed set of APIs for managing deployments
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@qernal.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { FunctionCompliance } from '../models/FunctionCompliance.ts';
import { FunctionDeployment } from '../models/FunctionDeployment.ts';
import { FunctionEnv } from '../models/FunctionEnv.ts';
import { FunctionRoute } from '../models/FunctionRoute.ts';
import { FunctionScaling } from '../models/FunctionScaling.ts';
import { FunctionSize } from '../models/FunctionSize.ts';
import { FunctionType } from '../models/FunctionType.ts';
import { HttpFile } from '../http/http.ts';

/**
* Function
*/
export class Function {
    /**
    * ID of the function
    */
    'id': string;
    /**
    * ID of the project this function belongs to
    */
    'project_id': string;
    /**
    * Function spec version
    */
    'version': FunctionVersionEnum;
    /**
    * Name of the function
    */
    'name': string;
    /**
    * Description of what the function does
    */
    'description': string;
    /**
    * Path to container image
    */
    'image': string;
    /**
    * Function revision
    */
    'revision': string;
    'type': FunctionType;
    'size': FunctionSize;
    /**
    * Port the application runs on
    */
    'port': number;
    /**
    * The public route/path to this function, only applicable to http type functions
    */
    'routes'?: Array<FunctionRoute>;
    'scaling': FunctionScaling;
    /**
    * List of deployments for this function
    */
    'deployments': Array<FunctionDeployment>;
    /**
    * List of environment variables for secrets
    */
    'secrets': Array<FunctionEnv>;
    /**
    * Tags to limit deployment
    */
    'compliance': Array<FunctionCompliance>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "project_id",
            "baseName": "project_id",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "version",
            "baseName": "version",
            "type": "FunctionVersionEnum",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string",
            "format": ""
        },
        {
            "name": "image",
            "baseName": "image",
            "type": "string",
            "format": ""
        },
        {
            "name": "revision",
            "baseName": "revision",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "FunctionType",
            "format": ""
        },
        {
            "name": "size",
            "baseName": "size",
            "type": "FunctionSize",
            "format": ""
        },
        {
            "name": "port",
            "baseName": "port",
            "type": "number",
            "format": ""
        },
        {
            "name": "routes",
            "baseName": "routes",
            "type": "Array<FunctionRoute>",
            "format": ""
        },
        {
            "name": "scaling",
            "baseName": "scaling",
            "type": "FunctionScaling",
            "format": ""
        },
        {
            "name": "deployments",
            "baseName": "deployments",
            "type": "Array<FunctionDeployment>",
            "format": ""
        },
        {
            "name": "secrets",
            "baseName": "secrets",
            "type": "Array<FunctionEnv>",
            "format": ""
        },
        {
            "name": "compliance",
            "baseName": "compliance",
            "type": "Array<FunctionCompliance>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return Function.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum FunctionVersionEnum {
    _1_0_0 = '1.0.0'
}

