/**
 * Chaos
 * Central Management API - publicly exposed set of APIs for managing deployments
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@qernal.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { FunctionReplicasAffinity } from '../models/FunctionReplicasAffinity.ts';
import { HttpFile } from '../http/http.ts';

/**
* Balancing logic
*/
export class FunctionReplicas {
    /**
    * Minimum number of replicas to have
    */
    'min': number;
    /**
    * Maximum number of replicas to have
    */
    'max': number;
    'affinity': FunctionReplicasAffinity;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "min",
            "baseName": "min",
            "type": "number",
            "format": ""
        },
        {
            "name": "max",
            "baseName": "max",
            "type": "number",
            "format": ""
        },
        {
            "name": "affinity",
            "baseName": "affinity",
            "type": "FunctionReplicasAffinity",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return FunctionReplicas.attributeTypeMap;
    }

    public constructor() {
    }
}

