/**
 * Chaos
 * Central Management API - publicly exposed set of APIs for managing deployments
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@qernal.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http.ts';

/**
* Scaling logic
*/
export class FunctionScaling {
    /**
    * CPU or Memory supported
    */
    'type': FunctionScalingTypeEnum;
    /**
    * For type to drop below before scale down
    */
    'low': number;
    /**
    * For type to go above before scale up
    */
    'high': number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "FunctionScalingTypeEnum",
            "format": ""
        },
        {
            "name": "low",
            "baseName": "low",
            "type": "number",
            "format": ""
        },
        {
            "name": "high",
            "baseName": "high",
            "type": "number",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return FunctionScaling.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum FunctionScalingTypeEnum {
    cpu = 'cpu',
    memory = 'memory'
}

