/**
 * Chaos
 * Central Management API - publicly exposed set of APIs for managing deployments
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@qernal.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { FunctionReplicas } from '../models/FunctionReplicas.ts';
import { Location } from '../models/Location.ts';
import { HttpFile } from '../http/http.ts';

export class FunctionDeployment {
    /**
    * ID of the deployment
    */
    'id'?: string;
    'location': Location;
    'replicas': FunctionReplicas;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "location",
            "baseName": "location",
            "type": "Location",
            "format": ""
        },
        {
            "name": "replicas",
            "baseName": "replicas",
            "type": "FunctionReplicas",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return FunctionDeployment.attributeTypeMap;
    }

    public constructor() {
    }
}

