/* tslint:disable */
/* eslint-disable */
/**
 * Chaos
 * Central Management API - publicly exposed set of APIs for managing deployments
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@qernal.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { OrganisationResponse } from './OrganisationResponse';
import {
    OrganisationResponseFromJSON,
    OrganisationResponseFromJSONTyped,
    OrganisationResponseToJSON,
} from './OrganisationResponse';
import type { PaginationMeta } from './PaginationMeta';
import {
    PaginationMetaFromJSON,
    PaginationMetaFromJSONTyped,
    PaginationMetaToJSON,
} from './PaginationMeta';

/**
 * List organisations schema
 * @export
 * @interface ListOrganisationResponse
 */
export interface ListOrganisationResponse {
    /**
     * 
     * @type {PaginationMeta}
     * @memberof ListOrganisationResponse
     */
    meta?: PaginationMeta;
    /**
     * 
     * @type {Array<OrganisationResponse>}
     * @memberof ListOrganisationResponse
     */
    data?: Array<OrganisationResponse>;
}

/**
 * Check if a given object implements the ListOrganisationResponse interface.
 */
export function instanceOfListOrganisationResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ListOrganisationResponseFromJSON(json: any): ListOrganisationResponse {
    return ListOrganisationResponseFromJSONTyped(json, false);
}

export function ListOrganisationResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListOrganisationResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'meta': !exists(json, 'meta') ? undefined : PaginationMetaFromJSON(json['meta']),
        'data': !exists(json, 'data') ? undefined : ((json['data'] as Array<any>).map(OrganisationResponseFromJSON)),
    };
}

export function ListOrganisationResponseToJSON(value?: ListOrganisationResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'meta': PaginationMetaToJSON(value.meta),
        'data': value.data === undefined ? undefined : ((value.data as Array<any>).map(OrganisationResponseToJSON)),
    };
}

