/**
 * Chaos
 * Central Management API - publicly exposed set of APIs for managing deployments
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@qernal.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { LogLog } from '../models/LogLog.ts';
import { HttpFile } from '../http/http.ts';

/**
* List of logs
*/
export class Log {
    /**
    * Container ID the log line is for
    */
    'container'?: string;
    /**
    * Function ID the log line is for
    */
    '_function'?: string;
    /**
    * Project ID the log line is for
    */
    'project'?: string;
    /**
    * Organisation ID the log line is for
    */
    'organisation'?: string;
    /**
    * Group ID the log line is for
    */
    'group'?: string;
    'log'?: LogLog;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "container",
            "baseName": "container",
            "type": "string",
            "format": ""
        },
        {
            "name": "_function",
            "baseName": "function",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "project",
            "baseName": "project",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "organisation",
            "baseName": "organisation",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "group",
            "baseName": "group",
            "type": "string",
            "format": "string"
        },
        {
            "name": "log",
            "baseName": "log",
            "type": "LogLog",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return Log.attributeTypeMap;
    }

    public constructor() {
    }
}

