/**
 * Chaos
 * Central Management API - publicly exposed set of APIs for managing deployments
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@qernal.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http.ts';

/**
* Log item
*/
export class LogLog {
    /**
    * Which log stream
    */
    'stream'?: LogLogStreamEnum;
    /**
    * If this was an event on the function or a log line
    */
    'kind'?: LogLogKindEnum;
    /**
    * An array of labels
    */
    'labels'?: Array<string>;
    /**
    * Log line type
    */
    'type'?: LogLogTypeEnum;
    /**
    * Log line
    */
    'line'?: string;
    /**
    * The date/time that this log was generated
    */
    'timestamp'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "stream",
            "baseName": "stream",
            "type": "LogLogStreamEnum",
            "format": ""
        },
        {
            "name": "kind",
            "baseName": "kind",
            "type": "LogLogKindEnum",
            "format": ""
        },
        {
            "name": "labels",
            "baseName": "labels",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "LogLogTypeEnum",
            "format": ""
        },
        {
            "name": "line",
            "baseName": "line",
            "type": "string",
            "format": ""
        },
        {
            "name": "timestamp",
            "baseName": "timestamp",
            "type": "string",
            "format": "datetime"
        }    ];

    static getAttributeTypeMap() {
        return LogLog.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum LogLogStreamEnum {
    stdout = 'stdout',
    stderr = 'stderr'
}
export enum LogLogKindEnum {
    event = 'event',
    log = 'log'
}
export enum LogLogTypeEnum {
    info = 'info',
    error = 'error'
}

