/**
 * Chaos
 * Central Management API - publicly exposed set of APIs for managing deployments
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@qernal.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http.ts';

export class LogsListFTimestampsParameter {
    /**
    * Restrict to after this timestamp
    */
    'after'?: string;
    /**
    * Resitrct to before this timestamp
    */
    'before'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "after",
            "baseName": "after",
            "type": "string",
            "format": ""
        },
        {
            "name": "before",
            "baseName": "before",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return LogsListFTimestampsParameter.attributeTypeMap;
    }

    public constructor() {
    }
}

