/**
 * Chaos
 * Central Management API - publicly exposed set of APIs for managing deployments
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@qernal.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { MetricResourceAggregationResourcesBucketsInnerHistogramBucketsInner } from '../models/MetricResourceAggregationResourcesBucketsInnerHistogramBucketsInner.ts';
import { HttpFile } from '../http/http.ts';

/**
* Histogram of resource usage
*/
export class MetricResourceAggregationResourcesBucketsInnerHistogram {
    /**
    * Array of resource usage by interval  > Note: A metric will have either a `counter` or `gauge` value 
    */
    'buckets'?: Array<MetricResourceAggregationResourcesBucketsInnerHistogramBucketsInner>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "buckets",
            "baseName": "buckets",
            "type": "Array<MetricResourceAggregationResourcesBucketsInnerHistogramBucketsInner>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return MetricResourceAggregationResourcesBucketsInnerHistogram.attributeTypeMap;
    }

    public constructor() {
    }
}

