/**
 * Chaos
 * Central Management API - publicly exposed set of APIs for managing deployments
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@qernal.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { MetricResourceAggregationResourcesBucketsInner } from '../models/MetricResourceAggregationResourcesBucketsInner.ts';
import { HttpFile } from '../http/http.ts';

/**
* Resource(s) aggregation
*/
export class MetricResourceAggregationResources {
    /**
    * Array of unqiue resources
    */
    'buckets'?: Array<MetricResourceAggregationResourcesBucketsInner>;
    /**
    * Upper bound of error in document count
    */
    'doc_count_error_upper_bound'?: number;
    /**
    * Sum of other document counts
    */
    'sum_other_doc_count'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "buckets",
            "baseName": "buckets",
            "type": "Array<MetricResourceAggregationResourcesBucketsInner>",
            "format": ""
        },
        {
            "name": "doc_count_error_upper_bound",
            "baseName": "doc_count_error_upper_bound",
            "type": "number",
            "format": ""
        },
        {
            "name": "sum_other_doc_count",
            "baseName": "sum_other_doc_count",
            "type": "number",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return MetricResourceAggregationResources.attributeTypeMap;
    }

    public constructor() {
    }
}

