/**
 * Chaos
 * Central Management API - publicly exposed set of APIs for managing deployments
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@qernal.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { MetricResourceAggregationResourcesBucketsInnerHistogramBucketsInnerCounter } from '../models/MetricResourceAggregationResourcesBucketsInnerHistogramBucketsInnerCounter.ts';
import { MetricResourceAggregationResourcesBucketsInnerHistogramBucketsInnerGauge } from '../models/MetricResourceAggregationResourcesBucketsInnerHistogramBucketsInnerGauge.ts';
import { HttpFile } from '../http/http.ts';

export class MetricResourceAggregationResourcesBucketsInnerHistogramBucketsInner {
    /**
    * Number of documents in the bucket
    */
    'doc_count'?: number;
    'counter'?: MetricResourceAggregationResourcesBucketsInnerHistogramBucketsInnerCounter;
    'gauge'?: MetricResourceAggregationResourcesBucketsInnerHistogramBucketsInnerGauge;
    /**
    * Histogram key (typically unix timestamp)
    */
    'key'?: number;
    /**
    * Histogram key as string/date-time
    */
    'key_as_string'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "doc_count",
            "baseName": "doc_count",
            "type": "number",
            "format": ""
        },
        {
            "name": "counter",
            "baseName": "counter",
            "type": "MetricResourceAggregationResourcesBucketsInnerHistogramBucketsInnerCounter",
            "format": ""
        },
        {
            "name": "gauge",
            "baseName": "gauge",
            "type": "MetricResourceAggregationResourcesBucketsInnerHistogramBucketsInnerGauge",
            "format": ""
        },
        {
            "name": "key",
            "baseName": "key",
            "type": "number",
            "format": ""
        },
        {
            "name": "key_as_string",
            "baseName": "key_as_string",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return MetricResourceAggregationResourcesBucketsInnerHistogramBucketsInner.attributeTypeMap;
    }

    public constructor() {
    }
}

