/**
 * Chaos
 * Central Management API - publicly exposed set of APIs for managing deployments
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@qernal.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http.ts';

/**
* Counter (monotonically incrementing)
*/
export class MetricResourceAggregationResourcesBucketsInnerHistogramBucketsInnerCounter {
    /**
    * Average counter value
    */
    'avg'?: number | null;
    /**
    * Number of counter values
    */
    'count'?: number | null;
    /**
    * Maximum counter value
    */
    'max'?: number | null;
    /**
    * Minimum counter value
    */
    'min'?: number | null;
    /**
    * Sum of counter values
    */
    'sum'?: number | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "avg",
            "baseName": "avg",
            "type": "number",
            "format": ""
        },
        {
            "name": "count",
            "baseName": "count",
            "type": "number",
            "format": ""
        },
        {
            "name": "max",
            "baseName": "max",
            "type": "number",
            "format": ""
        },
        {
            "name": "min",
            "baseName": "min",
            "type": "number",
            "format": ""
        },
        {
            "name": "sum",
            "baseName": "sum",
            "type": "number",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return MetricResourceAggregationResourcesBucketsInnerHistogramBucketsInnerCounter.attributeTypeMap;
    }

    public constructor() {
    }
}

