/**
 * Chaos
 * Central Management API - publicly exposed set of APIs for managing deployments
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@qernal.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { MetricResourceAggregationResources } from '../models/MetricResourceAggregationResources.ts';
import { HttpFile } from '../http/http.ts';

/**
* Metric resource aggregation
*/
export class MetricResourceAggregation {
    'resources'?: MetricResourceAggregationResources;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "resources",
            "baseName": "resources",
            "type": "MetricResourceAggregationResources",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return MetricResourceAggregation.attributeTypeMap;
    }

    public constructor() {
    }
}

