/**
 * Chaos
 * Central Management API - publicly exposed set of APIs for managing deployments
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@qernal.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { MetricHttpAggregationHttpCodes } from '../models/MetricHttpAggregationHttpCodes.ts';
import { HttpFile } from '../http/http.ts';

/**
* Metric http aggregation
*/
export class MetricHttpAggregation {
    'http_codes'?: MetricHttpAggregationHttpCodes;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "http_codes",
            "baseName": "http_codes",
            "type": "MetricHttpAggregationHttpCodes",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return MetricHttpAggregation.attributeTypeMap;
    }

    public constructor() {
    }
}

