/**
 * Chaos
 * Central Management API - publicly exposed set of APIs for managing deployments
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@qernal.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { MetricHttpAggregationHttpCodesBucketsInnerHistogram } from '../models/MetricHttpAggregationHttpCodesBucketsInnerHistogram.ts';
import { HttpFile } from '../http/http.ts';

/**
* HTTP status code bucket
*/
export class MetricHttpAggregationHttpCodesBucketsInner {
    /**
    * Number of documents in the bucket
    */
    'doc_count'?: number;
    'histogram'?: MetricHttpAggregationHttpCodesBucketsInnerHistogram;
    /**
    * HTTP status code, typical values will be;  - http-2xx - http-3xx - http-4xx - http-5xx  > Note: the \'xx\' is intentional and literal, all status codes within that range will be grouped 
    */
    'key'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "doc_count",
            "baseName": "doc_count",
            "type": "number",
            "format": ""
        },
        {
            "name": "histogram",
            "baseName": "histogram",
            "type": "MetricHttpAggregationHttpCodesBucketsInnerHistogram",
            "format": ""
        },
        {
            "name": "key",
            "baseName": "key",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return MetricHttpAggregationHttpCodesBucketsInner.attributeTypeMap;
    }

    public constructor() {
    }
}

