/**
 * Chaos
 * Central Management API - publicly exposed set of APIs for managing deployments
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@qernal.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http.ts';

/**
* Object date information
*/
export class ModelDate {
    /**
    * UTC creation datetime (ISO 8601 date format)
    */
    'created_at': string;
    /**
    * UTC update datetime (ISO 8601 date format)
    */
    'updated_at': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "created_at",
            "baseName": "created_at",
            "type": "string",
            "format": "datetime"
        },
        {
            "name": "updated_at",
            "baseName": "updated_at",
            "type": "string",
            "format": "datetime"
        }    ];

    static getAttributeTypeMap() {
        return ModelDate.attributeTypeMap;
    }

    public constructor() {
    }
}

