/* tslint:disable */
/* eslint-disable */
/**
 * Chaos
 * Central Management API - publicly exposed set of APIs for managing deployments
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@qernal.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Resource not found
 * @export
 * @interface NotFoundResponse
 */
export interface NotFoundResponse {
    /**
     * 
     * @type {string}
     * @memberof NotFoundResponse
     */
    message: string;
}

/**
 * Check if a given object implements the NotFoundResponse interface.
 */
export function instanceOfNotFoundResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "message" in value;

    return isInstance;
}

export function NotFoundResponseFromJSON(json: any): NotFoundResponse {
    return NotFoundResponseFromJSONTyped(json, false);
}

export function NotFoundResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): NotFoundResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'message': json['message'],
    };
}

export function NotFoundResponseToJSON(value?: NotFoundResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'message': value.message,
    };
}

