/* tslint:disable */
/* eslint-disable */
/**
 * Chaos
 * Central Management API - publicly exposed set of APIs for managing deployments
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@qernal.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Organisation body
 * @export
 * @interface OrganisationBody
 */
export interface OrganisationBody {
    /**
     * Organisation name
     * @type {string}
     * @memberof OrganisationBody
     */
    name: string;
}

/**
 * Check if a given object implements the OrganisationBody interface.
 */
export function instanceOfOrganisationBody(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "name" in value;

    return isInstance;
}

export function OrganisationBodyFromJSON(json: any): OrganisationBody {
    return OrganisationBodyFromJSONTyped(json, false);
}

export function OrganisationBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrganisationBody {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
    };
}

export function OrganisationBodyToJSON(value?: OrganisationBody | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
    };
}

