/**
 * Chaos
 * Central Management API - publicly exposed set of APIs for managing deployments
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@qernal.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http.ts';

export class OrganisationsListPageParameter {
    /**
    * Offset
    */
    'before'?: number;
    /**
    * Offset
    */
    'after'?: number;
    /**
    * Limit
    */
    'size'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "before",
            "baseName": "before",
            "type": "number",
            "format": ""
        },
        {
            "name": "after",
            "baseName": "after",
            "type": "number",
            "format": ""
        },
        {
            "name": "size",
            "baseName": "size",
            "type": "number",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return OrganisationsListPageParameter.attributeTypeMap;
    }

    public constructor() {
    }
}

