/* tslint:disable */
/* eslint-disable */
/**
 * Chaos
 * Central Management API - publicly exposed set of APIs for managing deployments
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@qernal.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Organisation response
 * @export
 * @interface OrganisationResponse
 */
export interface OrganisationResponse {
    /**
     * Organisation id
     * @type {string}
     * @memberof OrganisationResponse
     */
    id: string;
    /**
     * User id
     * @type {string}
     * @memberof OrganisationResponse
     */
    userId: string;
    /**
     * Organisation name
     * @type {string}
     * @memberof OrganisationResponse
     */
    name: string;
}

/**
 * Check if a given object implements the OrganisationResponse interface.
 */
export function instanceOfOrganisationResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "userId" in value;
    isInstance = isInstance && "name" in value;

    return isInstance;
}

export function OrganisationResponseFromJSON(json: any): OrganisationResponse {
    return OrganisationResponseFromJSONTyped(json, false);
}

export function OrganisationResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrganisationResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'userId': json['user_id'],
        'name': json['name'],
    };
}

export function OrganisationResponseToJSON(value?: OrganisationResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'user_id': value.userId,
        'name': value.name,
    };
}

