/* tslint:disable */
/* eslint-disable */
/**
 * Chaos
 * Central Management API - publicly exposed set of APIs for managing deployments
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@qernal.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Links object for pagination use
 * @export
 * @interface PaginationLinks
 */
export interface PaginationLinks {
    /**
     * 
     * @type {string}
     * @memberof PaginationLinks
     */
    prev: string;
    /**
     * 
     * @type {string}
     * @memberof PaginationLinks
     */
    next: string;
}

/**
 * Check if a given object implements the PaginationLinks interface.
 */
export function instanceOfPaginationLinks(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "prev" in value;
    isInstance = isInstance && "next" in value;

    return isInstance;
}

export function PaginationLinksFromJSON(json: any): PaginationLinks {
    return PaginationLinksFromJSONTyped(json, false);
}

export function PaginationLinksFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginationLinks {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'prev': json['prev'],
        'next': json['next'],
    };
}

export function PaginationLinksToJSON(value?: PaginationLinks | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'prev': value.prev,
        'next': value.next,
    };
}

