/**
 * Chaos
 * Central Management API - publicly exposed set of APIs for managing deployments
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@qernal.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { PaginationLinks } from '../models/PaginationLinks.ts';
import { HttpFile } from '../http/http.ts';

/**
* Meta object for pagination use
*/
export class PaginationMeta {
    'results': number;
    'start': number;
    'end': number;
    'pages': number;
    'links': PaginationLinks;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "results",
            "baseName": "results",
            "type": "number",
            "format": ""
        },
        {
            "name": "start",
            "baseName": "start",
            "type": "number",
            "format": ""
        },
        {
            "name": "end",
            "baseName": "end",
            "type": "number",
            "format": ""
        },
        {
            "name": "pages",
            "baseName": "pages",
            "type": "number",
            "format": ""
        },
        {
            "name": "links",
            "baseName": "links",
            "type": "PaginationLinks",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return PaginationMeta.attributeTypeMap;
    }

    public constructor() {
    }
}

