/* tslint:disable */
/* eslint-disable */
/**
 * Chaos
 * Central Management API - publicly exposed set of APIs for managing deployments
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@qernal.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Project response
 * @export
 * @interface ProjectResponse
 */
export interface ProjectResponse {
    /**
     * Project id
     * @type {string}
     * @memberof ProjectResponse
     */
    id: string;
    /**
     * Organisation id
     * @type {string}
     * @memberof ProjectResponse
     */
    orgId: string;
    /**
     * Project name
     * @type {string}
     * @memberof ProjectResponse
     */
    name: string;
}

/**
 * Check if a given object implements the ProjectResponse interface.
 */
export function instanceOfProjectResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "orgId" in value;
    isInstance = isInstance && "name" in value;

    return isInstance;
}

export function ProjectResponseFromJSON(json: any): ProjectResponse {
    return ProjectResponseFromJSONTyped(json, false);
}

export function ProjectResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProjectResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'orgId': json['org_id'],
        'name': json['name'],
    };
}

export function ProjectResponseToJSON(value?: ProjectResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'org_id': value.orgId,
        'name': value.name,
    };
}

