/* tslint:disable */
/* eslint-disable */
/**
 * Chaos
 * Central Management API - publicly exposed set of APIs for managing deployments
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@qernal.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Project body
 * @export
 * @interface ProjectBody
 */
export interface ProjectBody {
    /**
     * Organisation id
     * @type {string}
     * @memberof ProjectBody
     */
    orgId: string;
    /**
     * Project name
     * @type {string}
     * @memberof ProjectBody
     */
    name: string;
}

/**
 * Check if a given object implements the ProjectBody interface.
 */
export function instanceOfProjectBody(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "orgId" in value;
    isInstance = isInstance && "name" in value;

    return isInstance;
}

export function ProjectBodyFromJSON(json: any): ProjectBody {
    return ProjectBodyFromJSONTyped(json, false);
}

export function ProjectBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProjectBody {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'orgId': json['org_id'],
        'name': json['name'],
    };
}

export function ProjectBodyToJSON(value?: ProjectBody | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'org_id': value.orgId,
        'name': value.name,
    };
}

