/**
 * Chaos
 * Central Management API - publicly exposed set of APIs for managing deployments
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@qernal.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ProviderInnerLocations } from '../models/ProviderInnerLocations.ts';
import { HttpFile } from '../http/http.ts';

export class ProviderInner {
    'id'?: string;
    /**
    * Name of provider
    */
    'name'?: string;
    'locations'?: ProviderInnerLocations;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "locations",
            "baseName": "locations",
            "type": "ProviderInnerLocations",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ProviderInner.attributeTypeMap;
    }

    public constructor() {
    }
}

