/**
 * Chaos
 * Central Management API - publicly exposed set of APIs for managing deployments
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@qernal.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { SecretMetaResponseCertificatePayload } from '../models/SecretMetaResponseCertificatePayload.ts';
import { SecretMetaResponseRegistryPayload } from '../models/SecretMetaResponseRegistryPayload.ts';
import { HttpFile } from '../http/http.ts';

export class SecretResponsePayload {
    /**
    * Public SSL certificate
    */
    'certificate': string;
    /**
    * Registry domain
    */
    'registry': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "certificate",
            "baseName": "certificate",
            "type": "string",
            "format": "string"
        },
        {
            "name": "registry",
            "baseName": "registry",
            "type": "string",
            "format": "string"
        }    ];

    static getAttributeTypeMap() {
        return SecretResponsePayload.attributeTypeMap;
    }

    public constructor() {
    }
}

