/**
 * Chaos
 * Central Management API - publicly exposed set of APIs for managing deployments
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@qernal.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { SecretMetaResponseCertificatePayload } from '../models/SecretMetaResponseCertificatePayload.ts';
import { SecretMetaResponseDek } from '../models/SecretMetaResponseDek.ts';
import { SecretMetaResponseRegistryPayload } from '../models/SecretMetaResponseRegistryPayload.ts';
import { HttpFile } from '../http/http.ts';

export class SecretMetaResponsePayload {
    /**
    * Public SSL certificate
    */
    'certificate': string;
    /**
    * Private registry domain/location, when using the private docker hub registry sepcify `docker.io` > Without http scheme 
    */
    'registry': string;
    /**
    * Base64 encoded DEK public key
    */
    '_public': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "certificate",
            "baseName": "certificate",
            "type": "string",
            "format": "string"
        },
        {
            "name": "registry",
            "baseName": "registry",
            "type": "string",
            "format": "hostname"
        },
        {
            "name": "_public",
            "baseName": "public",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return SecretMetaResponsePayload.attributeTypeMap;
    }

    public constructor() {
    }
}

