/**
 * Chaos
 * Central Management API - publicly exposed set of APIs for managing deployments
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@qernal.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http.ts';

/**
* DEK secret, `type: dek`
*/
export class SecretMetaResponseDek {
    /**
    * Base64 encoded DEK public key
    */
    '_public': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "_public",
            "baseName": "public",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return SecretMetaResponseDek.attributeTypeMap;
    }

    public constructor() {
    }
}

