/**
 * Chaos
 * Central Management API - publicly exposed set of APIs for managing deployments
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@qernal.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { SecretMetaResponsePayload } from '../models/SecretMetaResponsePayload.ts';
import { SecretMetaType } from '../models/SecretMetaType.ts';
import { SecretResponseDate } from '../models/SecretResponseDate.ts';
import { HttpFile } from '../http/http.ts';

/**
* Secret metadata response
*/
export class SecretMetaResponse {
    /**
    * Project name
    */
    'name': string;
    'type': SecretMetaType;
    'payload'?: SecretMetaResponsePayload;
    /**
    * Secret revision
    */
    'revision': number;
    'date': SecretResponseDate;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "SecretMetaType",
            "format": ""
        },
        {
            "name": "payload",
            "baseName": "payload",
            "type": "SecretMetaResponsePayload",
            "format": ""
        },
        {
            "name": "revision",
            "baseName": "revision",
            "type": "number",
            "format": ""
        },
        {
            "name": "date",
            "baseName": "date",
            "type": "SecretResponseDate",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return SecretMetaResponse.attributeTypeMap;
    }

    public constructor() {
    }
}



