/* tslint:disable */
/* eslint-disable */
/**
 * Chaos
 * Central Management API - publicly exposed set of APIs for managing deployments
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@qernal.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Unauthorised
 * @export
 * @interface UnauthorisedResponse
 */
export interface UnauthorisedResponse {
    /**
     * 
     * @type {string}
     * @memberof UnauthorisedResponse
     */
    message: string;
}

/**
 * Check if a given object implements the UnauthorisedResponse interface.
 */
export function instanceOfUnauthorisedResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "message" in value;

    return isInstance;
}

export function UnauthorisedResponseFromJSON(json: any): UnauthorisedResponse {
    return UnauthorisedResponseFromJSONTyped(json, false);
}

export function UnauthorisedResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UnauthorisedResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'message': json['message'],
    };
}

export function UnauthorisedResponseToJSON(value?: UnauthorisedResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'message': value.message,
    };
}

